import { type ColorTokens, themes } from './color.js';
import { duration, easing, fontFamily, fontSize, radius, space } from './scale.js';

/**
 * CSS custom property generation (`BR-1583` — web consumes CSS custom properties).
 *
 * Emitted, not hand-written, so the CSS and the React Native constants cannot drift. A token
 * added to `scale.ts` appears in both without anyone remembering to update a stylesheet.
 */

/** `bgBase` → `--bg-base`. Purpose-named, per `BR-1219`. */
function kebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function colorBlock(colors: ColorTokens, indent: string): string {
  return (Object.keys(colors) as (keyof ColorTokens)[])
    .map((key) => `${indent}--${kebab(key)}: ${colors[key]};`)
    .join('\n');
}

function scaleBlock(indent: string): string {
  const lines: string[] = [];

  for (const [key, value] of Object.entries(space)) lines.push(`--space-${key}: ${value}px;`);
  for (const [key, value] of Object.entries(radius)) lines.push(`--radius-${key}: ${value}px;`);
  for (const [key, value] of Object.entries(duration)) lines.push(`--duration-${key}: ${value}ms;`);
  lines.push(`--ease: ${easing};`);

  for (const [key, value] of Object.entries(fontSize)) {
    lines.push(`--text-${key}: ${value.size}px;`);
    lines.push(`--leading-${key}: ${value.lineHeight}px;`);
  }
  for (const [key, value] of Object.entries(fontFamily)) lines.push(`--font-${key}: ${value};`);

  return lines.map((l) => `${indent}${l}`).join('\n');
}

/**
 * The full stylesheet.
 *
 * Dark is the default on `:root` — `12 §1`'s thesis is a dark-first product and `§3.1` is the
 * primary palette. `[data-theme]` is an explicit override in both directions, so a user choice
 * always wins over the OS; the `prefers-color-scheme` block only applies when no choice has been
 * made. Getting that precedence wrong is how a theme toggle appears to do nothing on a machine
 * set to light.
 */
export function generateCss(): string {
  return `/*
 * GENERATED by @josam/tokens — do not edit.
 * Source: packages/tokens/src/{color,scale}.ts, from 12 §3, §4.2 and §5.
 *
 * BR-1583 — packages/tokens is the single source for colour, spacing, type, radius and motion.
 * BR-1220 — a raw hex value in a component fails the build. Use these variables.
 * BR-1219 — reference --accent, never --gold. Names describe purpose, not appearance.
 */

:root {
${colorBlock(themes.dark, '  ')}

${scaleBlock('  ')}
}

:root[data-theme='light'] {
${colorBlock(themes.light, '  ')}
}

:root[data-theme='dark'] {
${colorBlock(themes.dark, '  ')}
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
${colorBlock(themes.light, '    ')}
  }
}

/* BR-1231 — prefers-reduced-motion disables all non-essential motion, including the rail's
   momentum gradient. Durations collapse rather than transitions being individually unset, so a
   component written later cannot forget to honour it. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
    --duration-slow: 0ms;
  }
}
`;
}
