/**
 * `@josam/tokens` — the single source for colour, spacing, type, radius and motion (`BR-1583`,
 * `BR-1533`).
 *
 * Two consumers, one source:
 *   web    — `dist/tokens.css`, generated by `src/build-css.ts` at build time
 *   mobile — the exported constants below, used directly (`BR-190`)
 *
 * This package depends on nothing (`BR-1575` applies to `@josam/ui`; the same holds here for the
 * same reason — a token package that imports an app cannot be consumed by the other apps).
 */
export {
  type ColorTokenName,
  type ColorTokens,
  darkColors,
  lightColors,
  type ThemeName,
  themes,
} from './color.js';

export {
  duration,
  type DurationToken,
  easing,
  fontFamily,
  type FontFamilyToken,
  fontSize,
  type FontSizeToken,
  radius,
  type RadiusToken,
  space,
  type SpaceToken,
} from './scale.js';

export { generateCss } from './css.js';
