/**
 * `PH-1.8` — the permission registry. `BR-709`, `05 §5`, `FEAT-014`.
 *
 * **The single source file.** `BR-709`: the registry is generated from one place, so adding a
 * permission in code makes it assignable in the admin UI without a migration. The database table
 * is a PROJECTION of this array, reconciled on boot — never the other way round.
 *
 * ## This file is generated from `05`, and a spec asserts it still matches
 *
 * 174 permissions across 18 module groups. Every module's count matches `05 §5`'s summary table
 * independently — 11, 9, 17, 7, 25, 9, 6, 12, 5, 8, 7, 5, 9, 6, 8, 7, 9, 14 — which is a second
 * check on the extraction rather than a restatement of it.
 *
 * `permission-registry.spec.ts` re-derives this list from `05` and compares. Drift in either
 * direction fails: a permission added here but not to `05` is undocumented, and one added to `05`
 * but not here is unimplementable. Neither is caught by anything else.
 *
 * ## Descriptions are deliberately absent
 *
 * `TBL-008.description` is nullable bilingual JSONB, and `BR-953` requires `ar` whenever it is
 * present. `05` carries English descriptions only. Writing those in with an invented Arabic
 * translation would put 174 fabricated strings into the database that the primary audience reads
 * — worse than a null, and precisely what `BR-524` (Arabic is the source of truth) exists to
 * prevent. They land when there is a real translation. `SB-45`.
 */

export interface PermissionDefinition {
  /** `model:action` or `model:action.scope` — `05 §5`. */
  readonly key: string;
  readonly model: string;
  readonly action: string;
  readonly scope: string | null;
  /** `M01` … `M18`. Used by the admin UI to group, and by `is_orphaned` sweeps to scope. */
  readonly module: string;
}

export const PERMISSION_REGISTRY: readonly PermissionDefinition[] = [
  { key: 'user:read', model: 'user', action: 'read', scope: null, module: 'M01' },
  { key: 'user:read.pii', model: 'user', action: 'read', scope: 'pii', module: 'M01' },
  { key: 'user:create', model: 'user', action: 'create', scope: null, module: 'M01' },
  { key: 'user:update', model: 'user', action: 'update', scope: null, module: 'M01' },
  { key: 'user:delete', model: 'user', action: 'delete', scope: null, module: 'M01' },
  { key: 'user:deactivate', model: 'user', action: 'deactivate', scope: null, module: 'M01' },
  { key: 'profile:read.own', model: 'profile', action: 'read', scope: 'own', module: 'M01' },
  { key: 'profile:update.own', model: 'profile', action: 'update', scope: 'own', module: 'M01' },
  { key: 'session:read.own', model: 'session', action: 'read', scope: 'own', module: 'M01' },
  { key: 'session:delete.own', model: 'session', action: 'delete', scope: 'own', module: 'M01' },
  { key: 'session:delete.any', model: 'session', action: 'delete', scope: 'any', module: 'M01' },
  { key: 'role:read', model: 'role', action: 'read', scope: null, module: 'M02' },
  { key: 'role:create', model: 'role', action: 'create', scope: null, module: 'M02' },
  { key: 'role:update', model: 'role', action: 'update', scope: null, module: 'M02' },
  { key: 'role:delete', model: 'role', action: 'delete', scope: null, module: 'M02' },
  { key: 'permission:read', model: 'permission', action: 'read', scope: null, module: 'M02' },
  { key: 'permission:assign', model: 'permission', action: 'assign', scope: null, module: 'M02' },
  { key: 'staff:read', model: 'staff', action: 'read', scope: null, module: 'M02' },
  { key: 'staff:create', model: 'staff', action: 'create', scope: null, module: 'M02' },
  { key: 'staff:update', model: 'staff', action: 'update', scope: null, module: 'M02' },
  { key: 'product:read', model: 'product', action: 'read', scope: null, module: 'M03' },
  { key: 'product:create', model: 'product', action: 'create', scope: null, module: 'M03' },
  { key: 'product:update', model: 'product', action: 'update', scope: null, module: 'M03' },
  { key: 'product:archive', model: 'product', action: 'archive', scope: null, module: 'M03' },
  { key: 'price:manage', model: 'price', action: 'manage', scope: null, module: 'M03' },
  { key: 'coupon:read', model: 'coupon', action: 'read', scope: null, module: 'M03' },
  { key: 'coupon:create', model: 'coupon', action: 'create', scope: null, module: 'M03' },
  { key: 'coupon:update', model: 'coupon', action: 'update', scope: null, module: 'M03' },
  { key: 'order:read', model: 'order', action: 'read', scope: null, module: 'M03' },
  { key: 'order:read.amounts', model: 'order', action: 'read', scope: 'amounts', module: 'M03' },
  { key: 'transaction:read', model: 'transaction', action: 'read', scope: null, module: 'M03' },
  { key: 'invoice:read', model: 'invoice', action: 'read', scope: null, module: 'M03' },
  { key: 'refund:request', model: 'refund', action: 'request', scope: null, module: 'M03' },
  { key: 'refund:approve', model: 'refund', action: 'approve', scope: null, module: 'M03' },
  { key: 'subscription:read', model: 'subscription', action: 'read', scope: null, module: 'M03' },
  {
    key: 'subscription:update',
    model: 'subscription',
    action: 'update',
    scope: null,
    module: 'M03',
  },
  { key: 'payment:read', model: 'payment', action: 'read', scope: null, module: 'M03' },
  { key: 'entitlement:read', model: 'entitlement', action: 'read', scope: null, module: 'M04' },
  { key: 'entitlement:grant', model: 'entitlement', action: 'grant', scope: null, module: 'M04' },
  { key: 'entitlement:revoke', model: 'entitlement', action: 'revoke', scope: null, module: 'M04' },
  { key: 'entitlement:extend', model: 'entitlement', action: 'extend', scope: null, module: 'M04' },
  {
    key: 'entitlement:read.audit',
    model: 'entitlement',
    action: 'read',
    scope: 'audit',
    module: 'M04',
  },
  { key: 'quota:read', model: 'quota', action: 'read', scope: null, module: 'M04' },
  { key: 'quota:adjust', model: 'quota', action: 'adjust', scope: null, module: 'M04' },
  { key: 'course:read', model: 'course', action: 'read', scope: null, module: 'M05' },
  { key: 'course:create', model: 'course', action: 'create', scope: null, module: 'M05' },
  { key: 'course:update.own', model: 'course', action: 'update', scope: 'own', module: 'M05' },
  { key: 'course:update.any', model: 'course', action: 'update', scope: 'any', module: 'M05' },
  { key: 'course:delete', model: 'course', action: 'delete', scope: null, module: 'M05' },
  { key: 'course:archive', model: 'course', action: 'archive', scope: null, module: 'M05' },
  {
    key: 'course:publish.request',
    model: 'course',
    action: 'publish',
    scope: 'request',
    module: 'M05',
  },
  {
    key: 'course:publish.approve',
    model: 'course',
    action: 'publish',
    scope: 'approve',
    module: 'M05',
  },
  { key: 'section:create', model: 'section', action: 'create', scope: null, module: 'M05' },
  { key: 'section:update', model: 'section', action: 'update', scope: null, module: 'M05' },
  { key: 'section:delete', model: 'section', action: 'delete', scope: null, module: 'M05' },
  { key: 'lesson:create', model: 'lesson', action: 'create', scope: null, module: 'M05' },
  { key: 'lesson:update', model: 'lesson', action: 'update', scope: null, module: 'M05' },
  { key: 'lesson:delete', model: 'lesson', action: 'delete', scope: null, module: 'M05' },
  { key: 'lesson_note:read', model: 'lesson_note', action: 'read', scope: null, module: 'M05' },
  { key: 'lesson_note:update', model: 'lesson_note', action: 'update', scope: null, module: 'M05' },
  { key: 'video:upload', model: 'video', action: 'upload', scope: null, module: 'M05' },
  { key: 'video:delete', model: 'video', action: 'delete', scope: null, module: 'M05' },
  { key: 'resource:create', model: 'resource', action: 'create', scope: null, module: 'M05' },
  { key: 'resource:update', model: 'resource', action: 'update', scope: null, module: 'M05' },
  { key: 'resource:delete', model: 'resource', action: 'delete', scope: null, module: 'M05' },
  { key: 'media:read', model: 'media', action: 'read', scope: null, module: 'M05' },
  { key: 'media:upload', model: 'media', action: 'upload', scope: null, module: 'M05' },
  { key: 'media:delete', model: 'media', action: 'delete', scope: null, module: 'M05' },
  {
    key: 'content:version.restore',
    model: 'content',
    action: 'version',
    scope: 'restore',
    module: 'M05',
  },
  { key: 'lesson:play', model: 'lesson', action: 'play', scope: null, module: 'M06' },
  { key: 'progress:read.own', model: 'progress', action: 'read', scope: 'own', module: 'M06' },
  { key: 'progress:read.any', model: 'progress', action: 'read', scope: 'any', module: 'M06' },
  { key: 'progress:update.own', model: 'progress', action: 'update', scope: 'own', module: 'M06' },
  { key: 'progress:reset', model: 'progress', action: 'reset', scope: null, module: 'M06' },
  { key: 'note:crud.own', model: 'note', action: 'crud', scope: 'own', module: 'M06' },
  { key: 'bookmark:crud.own', model: 'bookmark', action: 'crud', scope: 'own', module: 'M06' },
  { key: 'unlock_rule:manage', model: 'unlock_rule', action: 'manage', scope: null, module: 'M06' },
  {
    key: 'unlock_rule:override',
    model: 'unlock_rule',
    action: 'override',
    scope: null,
    module: 'M06',
  },
  { key: 'goal:crud.own', model: 'goal', action: 'crud', scope: 'own', module: 'M07' },
  { key: 'goal:read.any', model: 'goal', action: 'read', scope: 'any', module: 'M07' },
  { key: 'streak:read.own', model: 'streak', action: 'read', scope: 'own', module: 'M07' },
  { key: 'streak:read.any', model: 'streak', action: 'read', scope: 'any', module: 'M07' },
  { key: 'streak:adjust', model: 'streak', action: 'adjust', scope: null, module: 'M07' },
  {
    key: 'achievement:read.own',
    model: 'achievement',
    action: 'read',
    scope: 'own',
    module: 'M07',
  },
  { key: 'quiz:read', model: 'quiz', action: 'read', scope: null, module: 'M08' },
  { key: 'quiz:create', model: 'quiz', action: 'create', scope: null, module: 'M08' },
  { key: 'quiz:update', model: 'quiz', action: 'update', scope: null, module: 'M08' },
  { key: 'quiz:delete', model: 'quiz', action: 'delete', scope: null, module: 'M08' },
  { key: 'quiz:publish', model: 'quiz', action: 'publish', scope: null, module: 'M08' },
  { key: 'question:crud', model: 'question', action: 'crud', scope: null, module: 'M08' },
  {
    key: 'question_bank:manage',
    model: 'question_bank',
    action: 'manage',
    scope: null,
    module: 'M08',
  },
  { key: 'attempt:read.own', model: 'attempt', action: 'read', scope: 'own', module: 'M08' },
  { key: 'attempt:read.any', model: 'attempt', action: 'read', scope: 'any', module: 'M08' },
  { key: 'attempt:reset', model: 'attempt', action: 'reset', scope: null, module: 'M08' },
  { key: 'grading:read', model: 'grading', action: 'read', scope: null, module: 'M08' },
  { key: 'grading:submit', model: 'grading', action: 'submit', scope: null, module: 'M08' },
  {
    key: 'certificate:read.own',
    model: 'certificate',
    action: 'read',
    scope: 'own',
    module: 'M09',
  },
  {
    key: 'certificate:read.any',
    model: 'certificate',
    action: 'read',
    scope: 'any',
    module: 'M09',
  },
  { key: 'certificate:issue', model: 'certificate', action: 'issue', scope: null, module: 'M09' },
  { key: 'certificate:revoke', model: 'certificate', action: 'revoke', scope: null, module: 'M09' },
  {
    key: 'certificate:reissue',
    model: 'certificate',
    action: 'reissue',
    scope: null,
    module: 'M09',
  },
  { key: 'ai:chat', model: 'ai', action: 'chat', scope: null, module: 'M10' },
  {
    key: 'ai_conversation:read.own',
    model: 'ai_conversation',
    action: 'read',
    scope: 'own',
    module: 'M10',
  },
  {
    key: 'ai_conversation:read.any',
    model: 'ai_conversation',
    action: 'read',
    scope: 'any',
    module: 'M10',
  },
  { key: 'ai_config:read', model: 'ai_config', action: 'read', scope: null, module: 'M10' },
  { key: 'ai_config:update', model: 'ai_config', action: 'update', scope: null, module: 'M10' },
  { key: 'ai_usage:read', model: 'ai_usage', action: 'read', scope: null, module: 'M10' },
  { key: 'ai:compare', model: 'ai', action: 'compare', scope: null, module: 'M10' },
  { key: 'ai:reindex', model: 'ai', action: 'reindex', scope: null, module: 'M10' },
  { key: 'qa_question:create', model: 'qa_question', action: 'create', scope: null, module: 'M11' },
  { key: 'qa_question:read', model: 'qa_question', action: 'read', scope: null, module: 'M11' },
  { key: 'qa_answer:create', model: 'qa_answer', action: 'create', scope: null, module: 'M11' },
  { key: 'qa_answer:update', model: 'qa_answer', action: 'update', scope: null, module: 'M11' },
  { key: 'qa:moderate', model: 'qa', action: 'moderate', scope: null, module: 'M11' },
  { key: 'qa:resolve', model: 'qa', action: 'resolve', scope: null, module: 'M11' },
  { key: 'qa:promote_to_kb', model: 'qa', action: 'promote_to_kb', scope: null, module: 'M11' },
  { key: 'review:create', model: 'review', action: 'create', scope: null, module: 'M12' },
  { key: 'review:read', model: 'review', action: 'read', scope: null, module: 'M12' },
  { key: 'review:approve', model: 'review', action: 'approve', scope: null, module: 'M12' },
  { key: 'review:reply', model: 'review', action: 'reply', scope: null, module: 'M12' },
  { key: 'review:moderate', model: 'review', action: 'moderate', scope: null, module: 'M12' },
  { key: 'device:read.own', model: 'device', action: 'read', scope: 'own', module: 'M13' },
  { key: 'device:read.any', model: 'device', action: 'read', scope: 'any', module: 'M13' },
  {
    key: 'device_transfer:request',
    model: 'device_transfer',
    action: 'request',
    scope: null,
    module: 'M13',
  },
  {
    key: 'device_transfer:approve',
    model: 'device_transfer',
    action: 'approve',
    scope: null,
    module: 'M13',
  },
  {
    key: 'device_transfer:approve.override',
    model: 'device_transfer',
    action: 'approve',
    scope: 'override',
    module: 'M13',
  },
  { key: 'device:unbind', model: 'device', action: 'unbind', scope: null, module: 'M13' },
  { key: 'playback_log:read', model: 'playback_log', action: 'read', scope: null, module: 'M13' },
  { key: 'abuse_flag:read', model: 'abuse_flag', action: 'read', scope: null, module: 'M13' },
  { key: 'abuse_flag:resolve', model: 'abuse_flag', action: 'resolve', scope: null, module: 'M13' },
  {
    key: 'notification:read.own',
    model: 'notification',
    action: 'read',
    scope: 'own',
    module: 'M14',
  },
  { key: 'notification:send', model: 'notification', action: 'send', scope: null, module: 'M14' },
  {
    key: 'announcement:create',
    model: 'announcement',
    action: 'create',
    scope: null,
    module: 'M14',
  },
  {
    key: 'email_template:read',
    model: 'email_template',
    action: 'read',
    scope: null,
    module: 'M14',
  },
  {
    key: 'email_template:update',
    model: 'email_template',
    action: 'update',
    scope: null,
    module: 'M14',
  },
  { key: 'email_budget:read', model: 'email_budget', action: 'read', scope: null, module: 'M14' },
  { key: 'ticket:create', model: 'ticket', action: 'create', scope: null, module: 'M15' },
  { key: 'ticket:read.own', model: 'ticket', action: 'read', scope: 'own', module: 'M15' },
  { key: 'ticket:read.any', model: 'ticket', action: 'read', scope: 'any', module: 'M15' },
  { key: 'ticket:reply', model: 'ticket', action: 'reply', scope: null, module: 'M15' },
  { key: 'ticket:assign', model: 'ticket', action: 'assign', scope: null, module: 'M15' },
  {
    key: 'ticket:update_status',
    model: 'ticket',
    action: 'update_status',
    scope: null,
    module: 'M15',
  },
  {
    key: 'ticket:internal_note',
    model: 'ticket',
    action: 'internal_note',
    scope: null,
    module: 'M15',
  },
  {
    key: 'canned_response:manage',
    model: 'canned_response',
    action: 'manage',
    scope: null,
    module: 'M15',
  },
  { key: 'admin:access', model: 'admin', action: 'access', scope: null, module: 'M16' },
  { key: 'dashboard:read', model: 'dashboard', action: 'read', scope: null, module: 'M16' },
  { key: 'setting:read', model: 'setting', action: 'read', scope: null, module: 'M16' },
  { key: 'setting:update', model: 'setting', action: 'update', scope: null, module: 'M16' },
  { key: 'audit_log:read', model: 'audit_log', action: 'read', scope: null, module: 'M16' },
  {
    key: 'approval_queue:read',
    model: 'approval_queue',
    action: 'read',
    scope: null,
    module: 'M16',
  },
  { key: 'user:impersonate', model: 'user', action: 'impersonate', scope: null, module: 'M16' },
  { key: 'report:revenue', model: 'report', action: 'revenue', scope: null, module: 'M17' },
  { key: 'report:enrollment', model: 'report', action: 'enrollment', scope: null, module: 'M17' },
  { key: 'report:completion', model: 'report', action: 'completion', scope: null, module: 'M17' },
  { key: 'report:dropoff', model: 'report', action: 'dropoff', scope: null, module: 'M17' },
  { key: 'report:engagement', model: 'report', action: 'engagement', scope: null, module: 'M17' },
  { key: 'report:ai_usage', model: 'report', action: 'ai_usage', scope: null, module: 'M17' },
  { key: 'report:quiz', model: 'report', action: 'quiz', scope: null, module: 'M17' },
  { key: 'report:support', model: 'report', action: 'support', scope: null, module: 'M17' },
  { key: 'report:export', model: 'report', action: 'export', scope: null, module: 'M17' },
  { key: 'translation:read', model: 'translation', action: 'read', scope: null, module: 'M18' },
  { key: 'translation:update', model: 'translation', action: 'update', scope: null, module: 'M18' },
  { key: 'page:read', model: 'page', action: 'read', scope: null, module: 'M18' },
  { key: 'page:update', model: 'page', action: 'update', scope: null, module: 'M18' },
  { key: 'page:publish', model: 'page', action: 'publish', scope: null, module: 'M18' },
  { key: 'article:create', model: 'article', action: 'create', scope: null, module: 'M18' },
  { key: 'article:update', model: 'article', action: 'update', scope: null, module: 'M18' },
  { key: 'article:publish', model: 'article', action: 'publish', scope: null, module: 'M18' },
  { key: 'legal:update', model: 'legal', action: 'update', scope: null, module: 'M18' },
  { key: 'system:health', model: 'system', action: 'health', scope: null, module: 'M18' },
  { key: 'backup:read', model: 'backup', action: 'read', scope: null, module: 'M18' },
  { key: 'backup:trigger', model: 'backup', action: 'trigger', scope: null, module: 'M18' },
  { key: 'job:read', model: 'job', action: 'read', scope: null, module: 'M18' },
  { key: 'job:retry', model: 'job', action: 'retry', scope: null, module: 'M18' },
] as const;

/** `05 §5` states 174. Exported so the sync can assert it rather than trust the array's length. */
export const PERMISSION_COUNT = 174;
